[custom]
;不要随意改变关键字，除非你知道你如何操作！
;根据acl4SSR规则改编
;推荐订阅更新时间 1天=24小时=1440分钟=86400秒
;2天=48小时=2880分钟=172800秒
;3天=72小时=4320分钟=259200秒
;7天=168小时=10080分钟=604800秒

;Clash.Easy
;Clash.Easy.yaml

;去广告：支持
;自动测速：不支持
;微软分流：不支持
;苹果分流：不支持
;增强中国IP段：不支持
;增强国外GFW：不支持

ruleset=🎯 全球直连,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/Directly1.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/Nodeselect1.list
ruleset=🛑 全球拦截,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/Prohibitconnect.list
ruleset=🛑 全球拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🛑 全球拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/Nodeselect2.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/Directly2.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL

custom_proxy_group=🚀 节点选择`select`[]🧐 智能推荐`[]♻️ AI极速`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🇺🇲 美国节点`[]🌏 全球节点
custom_proxy_group=🇭🇰 香港节点`select`(香港|HKG)
custom_proxy_group=🇸🇬 狮城节点`select`(新加坡|SGP)
custom_proxy_group=🇺🇲 美国节点`select`(美国|USA)
custom_proxy_group=🇯🇵 日本节点`select`(日本|JPN)
custom_proxy_group=🌏 全球节点`select`.*
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]DIRECT
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🛑 全球拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=♻️ AI极速`url-test`.*`http://clients3.google.com/generate_204`300,,50
custom_proxy_group=🧐 智能推荐`url-test`(新北中华电信|波特兰|下载节点|俄罗斯1)`http://clients3.google.com/generate_204`300,,50

enable_rule_generator=true
overwrite_original_rules=true

clash_rule_base=https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/GeneralConfig_no-ipv6_redir-host.yml

;luck
